---
apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: test
  namespace: test-stage
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.test: semver:v1.x.x-stage
spec:
  chartGitPath: test
  releaseName: test-stage
  values:
    test:
      image: whitehat/http-echo:v1.0.2-dev
